insert into insurance (InsuranceId, InsuranceName, InsuranceDescription, DossierId) values(501, 'diam. Sed', 'vulputate, lacus. Cras interdum. ', 20);
insert into insurance (InsuranceId, InsuranceName, InsuranceDescription, DossierId) values(502, 'eu lacus.', 'orci luctus et ultrices.', 21);
insert into insurance (InsuranceId, InsuranceName, InsuranceDescription, DossierId) values(503, 'accumsan laoreet', 'convallis convallis', 32);
insert into insurance (InsuranceId, InsuranceName, InsuranceDescription, DossierId) values(504, 'torquent per', 'Nunc ut erat. ,', 35);
insert into insurance (InsuranceId, InsuranceName, InsuranceDescription, DossierId) values(505, 'nibh. Phasellus', 'adipiscing elit.', 59);
insert into insurance (InsuranceId, InsuranceName, InsuranceDescription, DossierId) values(506, 'mattis ornare,', 'iaculis enim, sit amet.', 61);
insert into insurance (InsuranceId, InsuranceName, InsuranceDescription, DossierId) values(507, 'Aenean euismod', 'orci. Donec nibh.', 74);
insert into insurance (InsuranceId, InsuranceName, InsuranceDescription, DossierId) values(508, 'semper auctor.', 'eu lacus.', 75);
insert into insurance (InsuranceId, InsuranceName, InsuranceDescription, DossierId) values(509, 'quis, pede.', 'Cras sed leo.', 91);
insert into insurance (InsuranceId, InsuranceName, InsuranceDescription, DossierId) values(510, 'non enim', 'dui, in sodales.', 93);
