insert into Assurance (assuranceId, type, nom, description) values (5005, 'BAGGAGE', 'Botsford LLC', 'in leo maecenas pulvinar lobortis est');
insert into Assurance (assuranceId, type, nom, description) values (5004, 'BAGGAGE', 'Lehner, Fritsch and Beier', 'nam nulla integer pede justo');
insert into Assurance (assuranceId, type, nom, description) values (5008, 'ANNULATION', 'Mann Inc', 'venenatis lacinia aenean sit amet justo morbi');
insert into Assurance (assuranceId, type, nom, description) values (5010, 'RAPATRIEMENT', 'Ratke-Hackett', 'metus arcu adipiscing molestie hendrerit at vulputate');
insert into Assurance (assuranceId, type, nom, description) values (5008, 'ANNULATION', 'Collier, Collins and Fadel', 'parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum');
insert into Assurance (assuranceId, type, nom, description) values (5003, 'BAGGAGE', 'Funk-Beatty', 'nulla elit ac nulla sed vel');
insert into Assurance (assuranceId, type, nom, description) values (5004, 'ANNULATION', 'Schmitt, Herzog and Grady', 'ut erat id mauris vulputate elementum nullam');
insert into Assurance (assuranceId, type, nom, description) values (5000, 'ANNULATION', 'Barton-Douglas', 'mus vivamus vestibulum sagittis sapien cum sociis natoque');
insert into Assurance (assuranceId, type, nom, description) values (5000, 'RAPATRIEMENT', 'Gutmann-Kuhn', 'mi sit amet lobortis sapien sapien');
insert into Assurance (assuranceId, type, nom, description) values (5010, 'ANNULATION', 'Wuckert-Muller', 'nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque');
insert into Assurance (assuranceId, type, nom, description) values (5010, 'BAGGAGE', 'Nicolas, Marvin and Pfeffer', 'felis sed interdum venenatis turpis enim blandit mi');
insert into Assurance (assuranceId, type, nom, description) values (5004, 'BAGGAGE', 'Bergnaum-Kunze', 'orci luctus et ultrices posuere cubilia curae mauris viverra');
insert into Assurance (assuranceId, type, nom, description) values (5008, 'ANNULATION', 'Turcotte LLC', 'dui maecenas tristique est et tempus semper');
insert into Assurance (assuranceId, type, nom, description) values (5003, 'BAGGAGE', 'Yundt-Ziemann', 'proin at turpis a pede posuere nonummy integer non velit');
insert into Assurance (assuranceId, type, nom, description) values (5005, 'BAGGAGE', 'Goyette-McLaughlin', 'amet nulla quisque arcu libero rutrum');
