insert into Destinations (continent, pays, region, description) values ('Australie', 'Palestinian Territory', 'Asia/Hebron', 'vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci');
insert into Destinations (continent, pays, region, description) values ('Amerique du Sud', 'France', 'Europe/Paris', 'imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit');
insert into Destinations (continent, pays, region, description) values ('Australie', 'Peru', 'America/Lima', 'rhoncus dui vel sem sed sagittis nam congue risus semper');
insert into Destinations (continent, pays, region, description) values ('Europe', 'Serbia', 'Europe/Belgrade', 'nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas');
insert into Destinations (continent, pays, region, description) values ('Afrique', 'Indonesia', 'Asia/Makassar', 'facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel');
insert into Destinations (continent, pays, region, description) values ('Europe', 'Philippines', 'Asia/Manila', 'at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio');
insert into Destinations (continent, pays, region, description) values ('Amerique du Nord', 'Serbia', 'Europe/Belgrade', 'sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer');
insert into Destinations (continent, pays, region, description) values ('Asie', 'China', 'Asia/Harbin', 'id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque');
insert into Destinations (continent, pays, region, description) values ('Europe', 'Philippines', 'Asia/Manila', 'non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus');
insert into Destinations (continent, pays, region, description) values ('Afrique', 'Greece', 'Europe/Athens', 'in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit');
insert into Destinations (continent, pays, region, description) values ('Amerique du Nord', 'Russia', 'Europe/Moscow', 'enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula');
insert into Destinations (continent, pays, region, description) values ('Europe', 'Estonia', 'Europe/Tallinn', 'felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar');
insert into Destinations (continent, pays, region, description) values ('Afrique', 'Syria', 'Europe/Istanbul', 'in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae');
insert into Destinations (continent, pays, region, description) values ('Amerique du Nord', 'Russia', 'Asia/Krasnoyarsk', 'vestibulum ante ipsum primis in faucibus orci luctus et ultrices');
insert into Destinations (continent, pays, region, description) values ('Afrique', 'Germany', 'Europe/Berlin', 'at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id');
insert into Destinations (continent, pays, region, description) values ('Amerique du Nord', 'China', 'Asia/Chongqing', 'in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue');
insert into Destinations (continent, pays, region, description) values ('Amerique du Sud', 'Russia', 'Asia/Almaty', 'justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna');
insert into Destinations (continent, pays, region, description) values ('Amerique du Nord', 'Ghana', 'Africa/Accra', 'duis at velit eu est congue elementum in hac habitasse');
insert into Destinations (continent, pays, region, description) values ('Australie', 'Russia', 'Europe/Moscow', 'ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus');
insert into Destinations (continent, pays, region, description) values ('Asie', 'Indonesia', 'Asia/Jakarta', 'sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi');
insert into Destinations (continent, pays, region, description) values ('Afrique', 'Russia', 'Asia/Yekaterinburg', 'sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis');
insert into Destinations (continent, pays, region, description) values ('Afrique', 'Japan', 'Asia/Tokyo', 'in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in');
insert into Destinations (continent, pays, region, description) values ('Amerique du Nord', 'Philippines', 'Asia/Manila', 'habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam');
insert into Destinations (continent, pays, region, description) values ('Amerique du Nord', 'Ecuador', 'America/Guayaquil', 'leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar');
insert into Destinations (continent, pays, region, description) values ('Afrique', 'Brazil', 'America/Sao_Paulo', 'mauris enim leo rhoncus sed vestibulum sit amet cursus id');
insert into Destinations (continent, pays, region, description) values ('Asie', 'Indonesia', 'Asia/Jakarta', 'mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis');
insert into Destinations (continent, pays, region, description) values ('Amerique du Nord', 'China', 'Asia/Shanghai', 'eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci');
insert into Destinations (continent, pays, region, description) values ('Australie', 'Portugal', 'Europe/Lisbon', 'vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis');
insert into Destinations (continent, pays, region, description) values ('Amerique du Sud', 'Ukraine', 'Europe/Uzhgorod', 'nulla sed accumsan felis ut at dolor quis odio consequat');
insert into Destinations (continent, pays, region, description) values ('Asie', 'Indonesia', 'Asia/Makassar', 'dui vel sem sed sagittis nam congue risus semper porta volutpat');
insert into Destinations (continent, pays, region, description) values ('Amerique du Sud', 'China', 'Asia/Shanghai', 'ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor');
insert into Destinations (continent, pays, region, description) values ('Asie', 'China', 'Asia/Shanghai', 'volutpat in congue etiam justo etiam pretium iaculis justo in');
insert into Destinations (continent, pays, region, description) values ('Amerique du Sud', 'Mexico', 'America/Mexico_City', 'ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut');
insert into Destinations (continent, pays, region, description) values ('Amerique du Nord', 'Indonesia', 'Asia/Jakarta', 'at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit');
insert into Destinations (continent, pays, region, description) values ('Amerique du Sud', 'Japan', 'Asia/Tokyo', 'id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu');
insert into Destinations (continent, pays, region, description) values ('Europe', 'Poland', 'Europe/Warsaw', 'ligula nec sem duis aliquam convallis nunc proin at turpis a');
insert into Destinations (continent, pays, region, description) values ('Australie', 'Zambia', 'Africa/Lusaka', 'tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum');
insert into Destinations (continent, pays, region, description) values ('Europe', 'Indonesia', 'Asia/Jakarta', 'lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed');
insert into Destinations (continent, pays, region, description) values ('Asie', 'Myanmar', 'Asia/Rangoon', 'nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel');
insert into Destinations (continent, pays, region, description) values ('Asie', 'Afghanistan', 'Asia/Kabul', 'augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo');
insert into Destinations (continent, pays, region, description) values ('Afrique', 'Philippines', 'Asia/Manila', 'consequat lectus in est risus auctor sed tristique in tempus sit');
insert into Destinations (continent, pays, region, description) values ('Amerique du Nord', 'Nigeria', 'Africa/Lagos', 'platea dictumst maecenas ut massa quis augue luctus tincidunt nulla');
insert into Destinations (continent, pays, region, description) values ('Europe', 'Gambia', 'Africa/Banjul', 'maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut');
insert into Destinations (continent, pays, region, description) values ('Asie', 'United States', 'America/Chicago', 'lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non');
insert into Destinations (continent, pays, region, description) values ('Australie', 'Ecuador', 'America/Guayaquil', 'neque aenean auctor gravida sem praesent id massa id nisl');
insert into Destinations (continent, pays, region, description) values ('Europe', 'Azerbaijan', 'Asia/Baku', 'bibendum felis sed interdum venenatis turpis enim blandit mi in');
insert into Destinations (continent, pays, region, description) values ('Australie', 'China', 'Asia/Shanghai', 'justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et');
insert into Destinations (continent, pays, region, description) values ('Amerique du Sud', 'Japan', 'Asia/Tokyo', 'libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla');
insert into Destinations (continent, pays, region, description) values ('Asie', 'Thailand', 'Asia/Bangkok', 'nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et');
insert into Destinations (continent, pays, region, description) values ('Afrique', 'Philippines', 'Asia/Manila', 'bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui');
insert into Destinations (continent, pays, region, description) values ('Asie', 'Canada', 'America/Toronto', 'ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed');
insert into Destinations (continent, pays, region, description) values ('Amerique du Sud', 'Kazakhstan', 'Asia/Almaty', 'in eleifend quam a odio in hac habitasse platea dictumst maecenas');
insert into Destinations (continent, pays, region, description) values ('Amerique du Sud', 'China', 'Asia/Chongqing', 'nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta');
insert into Destinations (continent, pays, region, description) values ('Amerique du Nord', 'Russia', 'Europe/Moscow', 'vestibulum ante ipsum primis in faucibus orci luctus et ultrices');
insert into Destinations (continent, pays, region, description) values ('Australie', 'Russia', 'Europe/Moscow', 'donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi');
insert into Destinations (continent, pays, region, description) values ('Afrique', 'Poland', 'Europe/Warsaw', 'quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis');
insert into Destinations (continent, pays, region, description) values ('Asie', 'China', 'Asia/Chongqing', 'vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit');
insert into Destinations (continent, pays, region, description) values ('Amerique du Sud', 'Netherlands', 'Europe/Amsterdam', 'curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue');
insert into Destinations (continent, pays, region, description) values ('Afrique', 'China', 'Asia/Chongqing', 'at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae');
insert into Destinations (continent, pays, region, description) values ('Asie', 'Macedonia', 'Europe/Skopje', 'metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in');
insert into Destinations (continent, pays, region, description) values ('Asie', 'United States', 'America/Los_Angeles', 'dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper');
insert into Destinations (continent, pays, region, description) values ('Europe', 'China', 'Asia/Shanghai', 'justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in');
insert into Destinations (continent, pays, region, description) values ('Amerique du Nord', 'China', 'Asia/Harbin', 'ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae');
insert into Destinations (continent, pays, region, description) values ('Asie', 'Greece', 'Europe/Athens', 'luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at');
insert into Destinations (continent, pays, region, description) values ('Europe', 'France', 'Europe/Paris', 'convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo');
insert into Destinations (continent, pays, region, description) values ('Australie', 'Russia', 'Asia/Almaty', 'quis orci eget orci vehicula condimentum curabitur in libero ut');
insert into Destinations (continent, pays, region, description) values ('Amerique du Nord', 'Poland', 'Europe/Warsaw', 'interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel');
insert into Destinations (continent, pays, region, description) values ('Australie', 'Greece', 'Europe/Athens', 'convallis nunc proin at turpis a pede posuere nonummy integer non velit');
insert into Destinations (continent, pays, region, description) values ('Afrique', 'China', 'Asia/Chongqing', 'maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam');
insert into Destinations (continent, pays, region, description) values ('Asie', 'China', 'Asia/Shanghai', 'lorem id ligula suspendisse ornare consequat lectus in est risus auctor');
insert into Destinations (continent, pays, region, description) values ('Australie', 'Brazil', 'America/Sao_Paulo', 'viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere');
insert into Destinations (continent, pays, region, description) values ('Amerique du Nord', 'Sweden', 'Europe/Stockholm', 'congue elementum in hac habitasse platea dictumst morbi vestibulum velit');
insert into Destinations (continent, pays, region, description) values ('Australie', 'Russia', 'Asia/Yakutsk', 'dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat');
insert into Destinations (continent, pays, region, description) values ('Europe', 'Micronesia', 'Pacific/Pohnpei', 'augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante');
insert into Destinations (continent, pays, region, description) values ('Afrique', 'Sweden', 'Europe/Stockholm', 'enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin');
insert into Destinations (continent, pays, region, description) values ('Australie', 'China', 'Asia/Shanghai', 'semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum');
insert into Destinations (continent, pays, region, description) values ('Australie', 'Philippines', 'Asia/Manila', 'leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede');
insert into Destinations (continent, pays, region, description) values ('Europe', 'Togo', 'Africa/Lome', 'eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien');
insert into Destinations (continent, pays, region, description) values ('Amerique du Sud', 'China', 'Asia/Chongqing', 'magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere');
insert into Destinations (continent, pays, region, description) values ('Europe', 'Chile', 'America/Santiago', 'lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in');
insert into Destinations (continent, pays, region, description) values ('Asie', 'China', 'Asia/Shanghai', 'diam erat fermentum justo nec condimentum neque sapien placerat ante');
insert into Destinations (continent, pays, region, description) values ('Amerique du Nord', 'China', 'Asia/Chongqing', 'cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra');
insert into Destinations (continent, pays, region, description) values ('Asie', 'United States', 'America/Los_Angeles', 'urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla');
insert into Destinations (continent, pays, region, description) values ('Europe', 'Senegal', 'Africa/Dakar', 'ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla');
insert into Destinations (continent, pays, region, description) values ('Amerique du Nord', 'Sweden', 'Europe/Stockholm', 'phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin');
insert into Destinations (continent, pays, region, description) values ('Europe', 'Philippines', 'Asia/Manila', 'donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis');
insert into Destinations (continent, pays, region, description) values ('Afrique', 'Ukraine', 'Europe/Kiev', 'fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam');
insert into Destinations (continent, pays, region, description) values ('Amerique du Nord', 'Finland', 'Europe/Helsinki', 'neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia');
insert into Destinations (continent, pays, region, description) values ('Afrique', 'China', 'Asia/Chongqing', 'sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales');
insert into Destinations (continent, pays, region, description) values ('Europe', 'Honduras', 'America/Tegucigalpa', 'pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper');
insert into Destinations (continent, pays, region, description) values ('Afrique', 'China', 'Asia/Chongqing', 'vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo');
insert into Destinations (continent, pays, region, description) values ('Europe', 'Estonia', 'Europe/Helsinki', 'volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc');
insert into Destinations (continent, pays, region, description) values ('Amerique du Sud', 'Argentina', 'America/Argentina/Salta', 'curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi');
insert into Destinations (continent, pays, region, description) values ('Afrique', 'Philippines', 'Asia/Manila', 'metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet');
insert into Destinations (continent, pays, region, description) values ('Asie', 'Ukraine', 'Europe/Simferopol', 'sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc');
insert into Destinations (continent, pays, region, description) values ('Amerique du Nord', 'Canada', 'America/Edmonton', 'pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus');
insert into Destinations (continent, pays, region, description) values ('Australie', 'Colombia', 'America/Bogota', 'nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis');
insert into Destinations (continent, pays, region, description) values ('Amerique du Nord', 'Belarus', 'Europe/Minsk', 'in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus');
insert into Destinations (continent, pays, region, description) values ('Australie', 'Indonesia', 'Asia/Pontianak', 'potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut');
